### ISSUE TITLE
sugestão: publicação do template diretamente na galeria do overleaf

### ISSUE THREAD

**Issue by mpds** [equipe-customizacao-tese-lncc/tese_lncc#11]
Parece que é possível sincronizar projetos no overleaf diretamente com repositórios do github.
Uma vez que o projeto está lá, é possível submetê-lo para a galeria do site, onde as pessoas podem usar diretamente na plataforma, o que acho que facilita ainda mais. A vantagem do template estar sincronizado com esse repo é que sempre que ele for atualizado aqui, é possível enviar a atualização para a galeria também, pelo que entendi.

Alguns links sobre: 
* https://www.overleaf.com/learn/how-to/Can_I_create_my_own_LaTeX_templates%3F
* https://pt.overleaf.com/learn/how-to/How_do_I_update_a_template,_example_or_article_I've_published_in_the_Overleaf_gallery%3F
* https://pt.overleaf.com/learn/how-to/How_do_I_connect_an_Overleaf_project_with_a_repo_on_GitHub,_GitLab_or_BitBucket%3F

**Comment by weslleyspereira** [comment]
Muito bom! Você gostaria de conduzir o procedimento de inclusão no Overleaf? Se sim, eu te incluo na equipe.

Eu concordo com você que pode facilitar a vida dos discentes.. Além do mais, o preview do Overleaf já mostraria a cara do documento, o que é mais interessante.

**Comment by mpds** [comment]
> Você gostaria de conduzir o procedimento de inclusão no Overleaf?

Posso tentar realizar o procedimento, sim. Uma vez disponibilizado no Overleaf também posso adicionar o link no README do projeto aqui. Lembrando que, pelo que está descrito [aqui](https://pt.overleaf.com/learn/how-to/How_do_I_update_a_template,_example_or_article_I've_published_in_the_Overleaf_gallery%3F), sempre que o projeto for atualizado no github, deve ser manualmente atualizado do lado de lá também.

> Além do mais, o preview do Overleaf já mostraria a cara do documento, o que é mais interessante.

Verdade, bem notado.

Obrigado pelo feedback!

**Comment by weslleyspereira** [comment]
Boa demais! Acabei de te adicionar na equipe de customização :)

**Comment by mpds** [comment]
Adicionado ao README no commit #12
